apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  namespace: production
spec:
  selector:
    app: shopping-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api-deployment
  namespace: production
  labels:
    app: shopping-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-api
  template:
    metadata:
      labels:
        app: shopping-api
    spec:
      containers:
      - name: shopping-api
        image: localhost:5000/shopping-api
        ports:
        - containerPort: 8080
        env:
          - name: ConnectionString
            valueFrom:
              configMapKeyRef:
                name: config-shopping-list
                key: connection_string