apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend
  namespace: production
spec:
  selector:
    app: shopping-frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend-deployment
  namespace: production
  labels:
    app: shopping-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
      - name: shopping-frontend
        image: localhost:5000/shopping-frontend
        ports:
        - containerPort: 8000
          